[about]
## Author / Copyright notice
author=Gabriel Annell

description=Adds bookmark support. https://github.com/LGabAnnell/xournalpp-bookmarks-plugin

version=0.1

[default]
enabled=false

[plugin]
mainfile=main.lua
